name = "gleam_dotnet_stdlib"
version = "0.41.0"
gleam = ">= 0.32.0"
licences = ["Apache-2.0"]
description = "A Fork of the standard library for the Gleam programming language with .NET target support"

repository = { type = "github", user = "gleam-lang", repo = "stdlib" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[javascript.deno]
allow_read = ["./"]

[fsharp]
target_framework = "net8.0"
